###############################
# DO NOT EDIT THIS FILE!!!!!!!#
###############################
import datetime
from stock_data import Instrument
DATA = Instrument("JMMB GROUP 7.25% VR JMD CR PREFERENCE SHARES", "JMMB7.25C", "JMD", "PREFERENCE", "FINANCE", None, last_updated=1537152510.104654)