###############################
# DO NOT EDIT THIS FILE!!!!!!!#
###############################
import datetime
from stocks import Instrument
DATA = Instrument("Jamaica Public Service Co. 5%", "JPS5", "JMD", "PREFERENCE", "", None, last_updated=1526954847.362789)