###############################
# DO NOT EDIT THIS FILE!!!!!!!#
###############################
import datetime
from stocks import Instrument
INSTR_JMMB725C = Instrument("JMMB GROUP 7.25% VR JMD CR PREFERENCE SHARES", "JMMB725C", "JMD", "PREFERENCE", "FINANCE", Instrument.TradeDataBanks([Instrument.TradeData(datetime.date(2018, 4, 19), 2.0, 2.0, 0.0, 0.0, 100000000, 2.0, 2.0, 2.0, 2.0)]), last_updated=1524219260.170578)