###############################
# DO NOT EDIT THIS FILE!!!!!!!#
###############################
import datetime
from stocks import Instrument
DATA = Instrument("PROVEN 8.25 CUMULATIVE REDEEMABLE PREFERENCE SHARES", "PROVEN8.25", "JMD", "PREFERENCE", "FINANCE", None, last_updated=1526955148.147725)