###############################
# DO NOT EDIT THIS FILE!!!!!!!#
###############################
import datetime
from stocks import Instrument
INSTR_JMMB75NC = Instrument("JMMB GROUP 7.00% VR JMD CR PREFERENCE SHARES", "JMMB75NC", "JMD", "PREFERENCE", "FINANCE", Instrument.TradeDataBanks([Instrument.TradeData(datetime.date(2018, 4, 19), 0.0, 0.0, 0.0, 0.0, 0, 0.0, 0.0, 0.0, 2.0)]), last_updated=1524219256.77693)