###############################
# DO NOT EDIT THIS FILE!!!!!!!#
###############################
import datetime
from stocks import Instrument
DATA = Instrument("CAC 2000 9.5% CUMULATIVE REDEEMABLE PREF SHARES", "CAC9.50", "JMD", "PREFERENCE", "RETAIL", Instrument.TradeDataBanks([Instrument.TradeData(datetime.date(2018, 5, 11), 0.0, 0.0, 0.0, 0.0, 0, 0.0, 0.0, 0.0, 1.0), Instrument.TradeData(datetime.date(2018, 5, 14), 0.0, 0.0, 0.0, 0.0, 0, 0.0, 0.0, 0.0, 1.0), Instrument.TradeData(datetime.date(2018, 5, 15), 0.0, 0.0, 0.0, 0.0, 0, 0.0, 0.0, 0.0, 1.0), Instrument.TradeData(datetime.date(2018, 5, 16), 0.0, 0.0, 0.0, 0.0, 0, 0.0, 0.0, 0.0, 1.0), Instrument.TradeData(datetime.date(2018, 5, 17), 0.0, 0.0, 0.0, 0.0, 0, 0.0, 0.0, 0.0, 1.0), Instrument.TradeData(datetime.date(2018, 5, 18), 0.0, 0.0, 0.0, 0.0, 0, 0.0, 0.0, 0.0, 1.0), Instrument.TradeData(datetime.date(2018, 5, 21), 0.0, 0.0, 0.0, 0.0, 0, 0.0, 0.0, 0.0, 1.0)]), last_updated=1526955385.363617)