###############################
# DO NOT EDIT THIS FILE!!!!!!!#
###############################
import datetime
from stocks import Instrument
DATA = Instrument("JMMB GROUP 7.00% VR JMD CR PREFERENCE SHARES", "JMMB7.50NC", "JMD", "PREFERENCE", "FINANCE", None, last_updated=1526954948.574775)