###############################
# DO NOT EDIT THIS FILE!!!!!!!#
###############################
import datetime
from stock_data import Instrument
DATA = Instrument("JAMAICA PUBLIC SERVICE CO. 5%", "JPS5", "JMD", "PREFERENCE", "", None, last_updated=1537152468.01864)