###############################
# DO NOT EDIT THIS FILE!!!!!!!#
###############################
import datetime
from stock_data import Instrument
DATA = Instrument("Jamaica Public Service Co. 5%", "JPS5", "JMD", "PREFERENCE", "", None, last_updated=1530852814.915714)